import { Perfume } from '@/types/perfume';

const parseNotes = (notesString: string, family: string = 'floral'): any[] => {
  if (!notesString || notesString === 'NaN') return [];
  return notesString.split(/[,;]/).map(note => ({
    name: note.trim(),
    intensity: Math.floor(Math.random() * 3) + 4, // 4-6 for realistic range
    family: family as any
  })).filter(note => note.name.length > 0);
};

export const FEMININE_PERFUMES: Perfume[] = [
  {
    id: 'ch-carolina-herrera',
    name: 'CH',
    brand: 'CAROLINA HERRERA',
    gender: 'feminino',
    topNotes: parseNotes('Bergamota, Toranja, Limão Verdadeiro Amalfi, Fruta Tropical, Notas Aquáticas', 'citrus'),
    heartNotes: parseNotes('Jasmim, Flor de Laranjeira Africana, Canela, Tintura de Rosa, Pralinê', 'floral'),
    baseNotes: parseNotes('Sândalo, Patchouli, Madeira de Cashmere, Cedro da Virgínia, Almíscar, Camurça, Âmbar', 'woody'),
    description: 'Combina tradição clássica com inovação contemporânea, adicionando um toque de elegância ao dia a dia. É como uma carícia suave que permanece na pele, evocando memórias e emoções a cada respiração.',
    personalityTraits: ['Elegante', 'Clássica', 'Sofisticada', 'Memorável'],
    season: ['primavera', 'verão'],
    occasions: ['trabalho', 'casual', 'romântico'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 2007,
    affiliateLinks: [
      { store: 'Amazon', url: 'https://amzn.to/ch-herrera', price: 289.90, discount: 15 },
      { store: 'Sephora', url: 'https://sephora.com.br/ch', price: 299.90 },
    ]
  },
  {
    id: 'angel-mugler',
    name: 'ANGEL',
    brand: 'MUGLER',
    gender: 'feminino',
    topNotes: parseNotes('Melão, Côco, Tangerina, Cássia, Jasmin, Bergamota, Algodão-doce', 'gourmand'),
    heartNotes: parseNotes('Bergamota da Calábria, Mel, Damasco, Amora, Ameixa, Orquídea, Pêssego, Jasmin, Lírio-do-vale, Bagas vermelhas, Rosa', 'floral'),
    baseNotes: parseNotes('Praliné, Fava Tonka, Âmbar, Patchouli, Almíscar, Baunilha, Chocolate amargo, Caramelo', 'gourmand'),
    description: 'Representa a mulher paradoxal de Mugler, pura e sensual, terna e conquistadora. Uma vibração pura, transparente e ligeira, com uma nota azul para evocar o espaço infinito.',
    personalityTraits: ['Paradoxal', 'Sensual', 'Conquistadora', 'Celestial'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'romântico', 'especial'],
    sillage: 'muito-forte',
    longevity: 'excelente',
    year: 1992,
    affiliateLinks: [
      { store: 'Amazon', url: 'https://amzn.to/angel-mugler', price: 459.90, discount: 20 },
      { store: 'Época Cosméticos', url: 'https://epoca.com.br/angel', price: 479.90 },
    ]
  },
  {
    id: 'chanel-no5',
    name: 'NO. 5',
    brand: 'CHANEL',
    gender: 'feminino',
    topNotes: parseNotes('Aldeídos, Ylang-Ylang, Néroli, Bergamota, Limão', 'floral'),
    heartNotes: parseNotes('Íris, Rosa, Jasmim, Rosa de maio, Lírio-do-vale', 'floral'),
    baseNotes: parseNotes('Sândalo, Vetiver, Baunilha, Âmbar, Musgo de Carvalho', 'oriental'),
    description: 'O perfume mais icônico de todos os tempos. Uma composição atemporal que define elegância e feminilidade há mais de um século. A fragrância da mulher inesquecível.',
    personalityTraits: ['Icônica', 'Atemporal', 'Elegante', 'Inesquecível'],
    season: ['outono', 'inverno'],
    occasions: ['especial', 'noite', 'formal'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 1921,
    affiliateLinks: [
      { store: 'Amazon', url: 'https://amzn.to/chanel-no5', price: 689.90, discount: 10 },
      { store: 'Sephora', url: 'https://sephora.com.br/chanel-5', price: 699.90 },
    ]
  },
  {
    id: 'tom-ford-black-orchid',
    name: 'BLACK ORCHID',
    brand: 'TOM FORD',
    gender: 'feminino',
    topNotes: parseNotes('Trufa, Gardênia, Orquídea Negra, Frutas Negras, Ylang-Ylang, Bergamota', 'oriental'),
    heartNotes: parseNotes('Orquídea, Especiarias, Gardênia, Frutas Negras, Ylang-Ylang', 'floral'),
    baseNotes: parseNotes('Patchouli, Baunilha, Incenso, Âmbar, Sândalo, Vetiver', 'oriental'),
    description: 'Uma fragrância luxuosa e decadente que captura o mistério da noite. Sedutora e opulenta, para a mulher que não tem medo de sua própria sensualidade.',
    personalityTraits: ['Sedutora', 'Opulenta', 'Misteriosa', 'Luxuosa'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'romântico'],
    sillage: 'muito-forte',
    longevity: 'excelente',
    year: 2006
  },
  {
    id: 'maison-margiela-replica-beach-walk',
    name: 'REPLICA BEACH WALK',
    brand: 'MAISON MARGIELA',
    gender: 'feminino',
    topNotes: parseNotes('Limão, Bergamota, Pimenta Rosa', 'citrus'),
    heartNotes: parseNotes('Ylang-Ylang, Coco, Heliotropo', 'floral'),
    baseNotes: parseNotes('Almíscar, Cedro, Benzoin', 'oriental'),
    description: 'Evoca memórias de um verão perfeito à beira-mar. A sensação de areia quente, brisa salgada e liberdade absoluta capturada em uma fragrância.',
    personalityTraits: ['Nostálgica', 'Livre', 'Solar', 'Despreocupada'],
    season: ['primavera', 'verão'],
    occasions: ['casual', 'praia', 'viagem'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 2012
  },
  {
    id: 'le-labo-santal-33',
    name: 'SANTAL 33',
    brand: 'LE LABO',
    gender: 'feminino',
    topNotes: parseNotes('Violeta, Cardamomo, Íris, Ambroxan', 'woody'),
    heartNotes: parseNotes('Sândalo Australiano, Ambroxan, Cedro', 'woody'),
    baseNotes: parseNotes('Couro, Papiro, Âmbar', 'woody'),
    description: 'O sândalo reimaginado para a era moderna. Uma fragrância unissex sofisticada que captura a essência do oeste americano com elegância urbana.',
    personalityTraits: ['Sofisticada', 'Moderna', 'Unissex', 'Urbana'],
    season: ['outono', 'inverno'],
    occasions: ['casual', 'trabalho', 'urbano'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2011
  },
  {
    id: 'creed-aventus-her',
    name: 'AVENTUS FOR HER',
    brand: 'CREED',
    gender: 'feminino',
    topNotes: parseNotes('Maçã Verde, Limão, Bergamota, Pimenta Rosa', 'fresh'),
    heartNotes: parseNotes('Rosa, Sândalo, Estirax', 'floral'),
    baseNotes: parseNotes('Almíscar, Âmbar, Ylang-Ylang', 'oriental'),
    description: 'Criado para a mulher conquistadora e visionária. Uma fragrância que celebra o sucesso feminino com notas que inspiram confiança e determinação.',
    personalityTraits: ['Conquistadora', 'Visionária', 'Confiante', 'Determinada'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['trabalho', 'especial', 'poder'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2016
  },
  {
    id: 'la-vie-est-belle',
    name: 'LA VIE EST BELLE',
    brand: 'LANCOME',
    gender: 'feminino',
    topNotes: parseNotes('Cassis, Groselha Preta, Pêra', 'fresh'),
    heartNotes: parseNotes('Íris, Jasmin, Flor de Laranjeira', 'floral'),
    baseNotes: parseNotes('Patchouli, Fava Tonka, Baunilha, Pralinê', 'gourmand'),
    description: 'La Vie Est Belle é um convite: escreva a sua própria história, encontre o seu caminho, faça a felicidade à sua maneira. Representa a escolha de viver a vida a seu próprio modo e deixá-la ainda mais bela.',
    personalityTraits: ['Otimista', 'Autêntica', 'Feliz', 'Inspiradora'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['casual', 'trabalho', 'especial'],
    sillage: 'forte',
    longevity: 'boa',
    year: 2012
  },
  {
    id: 'byredo-bal-dafrique',
    name: "BAL D'AFRIQUE",
    brand: 'BYREDO',
    gender: 'feminino',
    topNotes: parseNotes('Bergamota, Limão, Néroli, Manjericão Africano', 'citrus'),
    heartNotes: parseNotes('Violet, Ciclâme, Rosa Africana', 'floral'),
    baseNotes: parseNotes('Vetiver, Cedro, Âmbar', 'woody'),
    description: 'Inspirada na cultura e música africana dos anos 1920 em Paris. Uma celebração vibrante da diversidade cultural e da alegria de viver.',
    personalityTraits: ['Vibrante', 'Cultural', 'Celebrativa', 'Diversa'],
    season: ['primavera', 'verão'],
    occasions: ['casual', 'artístico', 'cultural'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 2009
  },
  {
    id: 'diptyque-philosykos',
    name: 'PHILOSYKOS',
    brand: 'DIPTYQUE',
    gender: 'feminino',
    topNotes: parseNotes('Folha de Figueira, Figo Verde', 'green'),
    heartNotes: parseNotes('Figo, Leite de Figo, Folhas Verdes', 'green'),
    baseNotes: parseNotes('Cedro, Madeira de Figueira', 'woody'),
    description: 'A essência pura da figueira mediterrânea. Uma homenagem poética à árvore sagrada, capturando desde suas folhas verdes até seus frutos maduros.',
    personalityTraits: ['Naturalista', 'Poética', 'Mediterrânea', 'Pura'],
    season: ['primavera', 'verão'],
    occasions: ['casual', 'natural', 'artístico'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 1996
  },
  {
    id: 'ange-ou-demon',
    name: 'ANGE OU DEMON',
    brand: 'GIVENCHY',
    gender: 'feminino',
    topNotes: parseNotes('Tangerina, Açafrão, Tomilho Branco', 'citrus'),
    heartNotes: parseNotes('Lírio, Ylang-Ylang, Orquídea', 'floral'),
    baseNotes: parseNotes('Fava Tonka, Madeira de Carvalho', 'woody'),
    description: 'Inspirado na mulher encantadora, feita de uma elegância única. Uma fragrância enigmática, quase indecifrável. Sua aura é inexplicável e fica gravada na memória.',
    personalityTraits: ['Enigmática', 'Elegante', 'Memorável', 'Sofisticada'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'romântico'],
    sillage: 'forte',
    longevity: 'boa',
    year: 2006
  },
  {
    id: 'libre-ysl',
    name: 'LIBRE',
    brand: 'YVES SAINT LAURENT',
    gender: 'feminino',
    topNotes: parseNotes('Tangerina, Lavanda, Cassis, Petitgrain', 'citrus'),
    heartNotes: parseNotes('Jasmim, Lavanda, Flor de Laranjeira', 'floral'),
    baseNotes: parseNotes('Baunilha do Madagascar, Cedro, Âmbar-gris, Almíscar', 'oriental'),
    description: 'É uma fragrância audaciosa e elegante, que personifica a liberdade. Ideal para mulheres que desejam expressar sua personalidade forte e independente.',
    personalityTraits: ['Audaciosa', 'Independente', 'Forte', 'Livre'],
    season: ['primavera', 'verão'],
    occasions: ['casual', 'trabalho', 'especial'],
    sillage: 'forte',
    longevity: 'boa',
    year: 2019
  },
  {
    id: 'si-passione-armani',
    name: 'SI PASSIONE',
    brand: 'GIORGIO ARMANI',
    gender: 'feminino',
    topNotes: parseNotes('Pimenta Rosa, Pêra, Cassis, Toranja', 'fresh'),
    heartNotes: parseNotes('Rosa, Jasmim, Heliotrópio, Abacaxi', 'floral'),
    baseNotes: parseNotes('Cedro, Baunilha, Madeira de Âmbar, Patchouli', 'oriental'),
    description: 'A fragrância que traz um aroma intenso floral sensual e frutado, numa combinação marcante para uma mulher confiante, ousada e decidida – que se atreve a dizer sim.',
    personalityTraits: ['Confiante', 'Ousada', 'Decidida', 'Apaixonada'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['romântico', 'especial', 'noite'],
    sillage: 'forte',
    longevity: 'boa',
    year: 2017
  },
  {
    id: 'linterdit-givenchy',
    name: "L'INTERDIT",
    brand: 'GIVENCHY',
    gender: 'feminino',
    topNotes: parseNotes('Bergamota, Pêra, Cereja Amarga', 'fresh'),
    heartNotes: parseNotes('Tuberosa, Flor de Laranjeira, Jasmim Sambac', 'floral'),
    baseNotes: parseNotes('Patchouli, Vetiver, Ambroxan, Caramelo, Baunilha', 'oriental'),
    description: 'L\'Interdit, um tributo à feminilidade ousada. Um convite para desafiar seus limites e explorar a emoção do proibido. Uma fragrância destemida que afirma que a audácia é a chave para a liberdade.',
    personalityTraits: ['Ousada', 'Destemida', 'Proibida', 'Libertadora'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'romântico'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2018
  },
  {
    id: 'good-girl-herrera',
    name: 'GOOD GIRL',
    brand: 'CAROLINA HERRERA',
    gender: 'feminino',
    topNotes: parseNotes('Limão, Amêndoa, Café', 'gourmand'),
    heartNotes: parseNotes('Tuberosa, Jasmim Sambac, Rosa Búlgara', 'floral'),
    baseNotes: parseNotes('Fava Tonka, Cacau, Sândalo, Almíscar, Pralinê, Mel, Orris, Âmbar, Cedro, Canela', 'oriental'),
    description: 'It\'s so good to be bad. Uma fragrância que celebra a dualidade feminina - boa menina de dia, má menina de noite. O salto icônico reflete essa personalidade multifacetada.',
    personalityTraits: ['Dual', 'Sofisticada', 'Travessa', 'Multifacetada'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'romântico'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2016
  },
  {
    id: 'flowerbomb-viktor-rolf',
    name: 'FLOWERBOMB',
    brand: 'VIKTOR & ROLF',
    gender: 'feminino',
    topNotes: parseNotes('Chá, Bergamota, Osmanthus', 'fresh'),
    heartNotes: parseNotes('Jasmim Sambac, Rosa, Catléia, Frésia', 'floral'),
    baseNotes: parseNotes('Patchouli, Almíscar, Baunilha', 'oriental'),
    description: 'Uma explosão floral que transforma negatividade em positividade. Como uma bomba de flores que espalha alegria e energia por onde passa.',
    personalityTraits: ['Explosiva', 'Positiva', 'Energética', 'Transformadora'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['casual', 'especial', 'celebração'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2005
  },
  {
    id: 'miss-dior',
    name: 'MISS DIOR',
    brand: 'DIOR',
    gender: 'feminino',
    topNotes: parseNotes('Mandarina Siciliana, Cassis', 'citrus'),
    heartNotes: parseNotes('Rosa Grasse, Peônia, Íris', 'floral'),
    baseNotes: parseNotes('Patchouli, Almíscar Branco', 'woody'),
    description: 'A nova Miss Dior é radiante, rebelde e romântica. Uma fragrância que celebra o amor em todas as suas formas - primeira vista, primeira vez, para sempre.',
    personalityTraits: ['Radiante', 'Rebelde', 'Romântica', 'Apaixonada'],
    season: ['primavera', 'verão'],
    occasions: ['romântico', 'casual', 'especial'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 2017
  },
  {
    id: 'coco-mademoiselle',
    name: 'COCO MADEMOISELLE',
    brand: 'CHANEL',
    gender: 'feminino',
    topNotes: parseNotes('Laranja, Bergamota, Toranja', 'citrus'),
    heartNotes: parseNotes('Rosa, Jasmim, Mimosa, Lychee', 'floral'),
    baseNotes: parseNotes('Patchouli, Baunilha, Tonka, Almíscar Branco', 'oriental'),
    description: 'O espírito rebelde e elegante de Coco Chanel em uma fragrância moderna. Para a mulher audaciosa que escreve suas próprias regras.',
    personalityTraits: ['Rebelde', 'Elegante', 'Audaciosa', 'Independente'],
    season: ['outono', 'inverno'],
    occasions: ['trabalho', 'especial', 'poder'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2001
  },
  {
    id: 'olympea-rabanne',
    name: 'OLYMPÉA',
    brand: 'PACO RABANNE',
    gender: 'feminino',
    topNotes: parseNotes('Mandarina Verde, Gengibre, Pêra de Água', 'fresh'),
    heartNotes: parseNotes('Jasmim, Sal Marinho, Hidrângea', 'floral'),
    baseNotes: parseNotes('Baunilha, Sândalo, Âmbar-gris, Cashmere', 'oriental'),
    description: 'Para a mulher que vive como uma deusa moderna. Poderosa, sensual e divina. Uma fragrância que celebra a força feminina ancestral.',
    personalityTraits: ['Divina', 'Poderosa', 'Sensual', 'Ancestral'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'poder'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2015
  }
];

export const MASCULINE_PERFUMES: Perfume[] = [
  {
    id: 'versace-pour-homme',
    name: 'POUR HOMME',
    brand: 'VERSACE',
    gender: 'masculino',
    topNotes: parseNotes('Limão, Bergamota, Néroli, Rosa Centifolia', 'citrus'),
    heartNotes: parseNotes('Jacinto, Cedro, Sálvia Esclaréia, Gerânio', 'aromatic'),
    baseNotes: parseNotes('Fava Tonka, Almíscar, Âmbar', 'oriental'),
    description: 'Um perfume com um aroma surpreendente, clássico e ao mesmo tempo contemporâneo. Criado para o homem dinâmico e empreendedor, que transmite seu caráter forte e impetuoso.',
    personalityTraits: ['Dinâmico', 'Empreendedor', 'Forte', 'Impetuoso'],
    season: ['primavera', 'verão'],
    occasions: ['trabalho', 'casual', 'esporte'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 2008
  },
  {
    id: 'acqua-di-gio',
    name: 'ACQUA DI GIO',
    brand: 'GIORGIO ARMANI',
    gender: 'masculino',
    topNotes: parseNotes('Bergamota, Limão, Lima, Mandarina', 'citrus'),
    heartNotes: parseNotes('Acorde Marinho, Coentro, Frésia, Ciclâme', 'fresh'),
    baseNotes: parseNotes('Cedro, Musgo, Musk, Patchuli', 'woody'),
    description: 'Proporciona uma sensação de frescor e equilíbrio. Um homem em harmonia com o mar, confiante e seguro de si. A essência de um homem que não finge ser nada além do que é.',
    personalityTraits: ['Autêntico', 'Natural', 'Confiante', 'Equilibrado'],
    season: ['primavera', 'verão'],
    occasions: ['casual', 'esporte', 'praia'],
    sillage: 'moderado',
    longevity: 'moderada',
    year: 1996
  },
  {
    id: 'sauvage-dior',
    name: 'SAUVAGE',
    brand: 'DIOR',
    gender: 'masculino',
    topNotes: parseNotes('Pimenta, Bergamota da Calabria', 'aromatic'),
    heartNotes: parseNotes('Gerânio, Lavanda, Pimenta de Szechuan, Elemi, Pimenta rosa, Vetiver', 'aromatic'),
    baseNotes: parseNotes('Cedro, Ládano, Ambroxam', 'woody'),
    description: 'Uma masculinidade forte e inconfundível, tal como a imagem de um homem que transcende o tempo e a moda. Traz notas intensas e nobres que revelam a inspiração selvagem.',
    personalityTraits: ['Selvagem', 'Intenso', 'Nobre', 'Atemporal'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'romântico'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2015
  },
  {
    id: 'bleu-de-chanel',
    name: 'BLEU DE CHANEL',
    brand: 'CHANEL',
    gender: 'masculino',
    topNotes: parseNotes('Raspas de Limão, Bergamota, Hortelã, Artemísia', 'citrus'),
    heartNotes: parseNotes('Lavanda, Abacaxi, Gerânio, Notas Verdes', 'aromatic'),
    baseNotes: parseNotes('Sândalo, Cedro, Madeira de Âmbar, Iso E Super, Fava Tonka', 'woody'),
    description: 'Para o homem que desafia as convenções e resiste à monotonia do dia a dia. Uma mistura provocante de notas cítricas e amadeiradas que liberta os sentidos.',
    personalityTraits: ['Desafiador', 'Provocante', 'Livre', 'Sensual'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['trabalho', 'casual', 'especial'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2010
  },
  {
    id: 'creed-aventus',
    name: 'AVENTUS',
    brand: 'CREED',
    gender: 'masculino',
    topNotes: parseNotes('Abacaxi, Maçã, Cassis, Bergamota', 'fresh'),
    heartNotes: parseNotes('Bétula, Rosa, Patchouli, Jasmim', 'woody'),
    baseNotes: parseNotes('Musgo de Carvalho, Almíscar, Âmbar-gris, Baunilha', 'woody'),
    description: 'Inspirado na vida dramática do imperador francês Napoleão Bonaparte. Para o homem que lidera pelo exemplo, criando seu próprio destino com determinação e sucesso.',
    personalityTraits: ['Líder', 'Determinado', 'Bem-sucedido', 'Imperial'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['trabalho', 'especial', 'poder'],
    sillage: 'muito-forte',
    longevity: 'excelente',
    year: 2010
  },
  {
    id: 'tom-ford-oud-wood',
    name: 'OUD WOOD',
    brand: 'TOM FORD',
    gender: 'masculino',
    topNotes: parseNotes('Pau-rosa, Cardamomo, Pimenta Rosa', 'woody'),
    heartNotes: parseNotes('Oud, Sândalo, Palisandro', 'woody'),
    baseNotes: parseNotes('Baunilha, Âmbar', 'oriental'),
    description: 'Uma interpretação ocidental sofisticada do oud tradicional. Rico, quente e opulento, mas surpreendentemente portável. O oud para iniciantes, mas também para conhecedores.',
    personalityTraits: ['Sofisticado', 'Rico', 'Opulento', 'Exótico'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'luxo'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2007
  },
  {
    id: 'le-male-jean-paul-gaultier',
    name: 'LE MÂLE',
    brand: 'JEAN PAUL GAULTIER',
    gender: 'masculino',
    topNotes: parseNotes('Artemísia, Bergamota, Cardamomo, Lavanda', 'aromatic'),
    heartNotes: parseNotes('Canela, Cumarina, Flor de Laranjeira', 'aromatic'),
    baseNotes: parseNotes('Sândalo, Baunilha, Cedro', 'oriental'),
    description: 'O primeiro perfume masculino em formato feminino. Revolucionário e provocativo, celebra a beleza masculina sem tabus. Para o homem que ousa ser diferente.',
    personalityTraits: ['Revolucionário', 'Provocativo', 'Ousado', 'Diferente'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'romântico'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 1995
  },
  {
    id: 'ysl-y-edp',
    name: 'Y',
    brand: 'YVES SAINT LAURENT',
    gender: 'masculino',
    topNotes: parseNotes('Maçã, Gengibre, Bergamota', 'fresh'),
    heartNotes: parseNotes('Salvia, Gerânio, Lírio-do-vale', 'aromatic'),
    baseNotes: parseNotes('Bálsamo do Peru, Cedro, Olíbano', 'woody'),
    description: 'Para o homem que ousa fazer a pergunta "Por quê?". Intenso, fresco e limpo, mas com profundidade. A fragrância do homem que conquista seus sonhos.',
    personalityTraits: ['Questionador', 'Intenso', 'Limpo', 'Sonhador'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['casual', 'trabalho', 'especial'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2017
  },
  {
    id: 'dolce-gabbana-the-one',
    name: 'THE ONE',
    brand: 'DOLCE & GABBANA',
    gender: 'masculino',
    topNotes: parseNotes('Coentro, Basilicão, Cardamomo, Bergamota', 'aromatic'),
    heartNotes: parseNotes('Gengibre, Flor de Laranjeira, Canela', 'spicy'),
    baseNotes: parseNotes('Cedro, Âmbar, Tabaco, Ambroxam', 'woody'),
    description: 'Para o homem que é "The One" - único, carismático e inesquecível. Uma fragrância quente e sensual que expressa paixão e masculinidade mediterrânea.',
    personalityTraits: ['Único', 'Carismático', 'Inesquecível', 'Apaixonado'],
    season: ['outono', 'inverno'],
    occasions: ['romântico', 'noite', 'especial'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 2008
  },
  {
    id: 'maison-margiela-by-the-fireplace',
    name: 'BY THE FIREPLACE',
    brand: 'MAISON MARGIELA',
    gender: 'masculino',
    topNotes: parseNotes('Pimenta Rosa, Laranja, Óleo de Cravo', 'spicy'),
    heartNotes: parseNotes('Castanha, Guaiacol, Juniper', 'woody'),
    baseNotes: parseNotes('Cashmeran, Baunilha, Peru Balm', 'oriental'),
    description: 'Evoca a memória de uma noite aconchegante ao pé da lareira. O calor, o conforto e a intimidade de momentos especiais capturados em fragrância.',
    personalityTraits: ['Aconchegante', 'Íntimo', 'Caloroso', 'Nostálgico'],
    season: ['outono', 'inverno'],
    occasions: ['casual', 'íntimo', 'conforto'],
    sillage: 'moderado',
    longevity: 'boa',
    year: 2015
  },
  {
    id: 'bulgari-man-black-cologne',
    name: 'MAN BLACK COLOGNE',
    brand: 'BULGARI',
    gender: 'masculino',
    topNotes: parseNotes('Bergamota, Pimenta Preta, Rum', 'spicy'),
    heartNotes: parseNotes('Tuberosa, Couro, Angelica', 'leather'),
    baseNotes: parseNotes('Âmbar, Benzoin, Guaiac Wood', 'oriental'),
    description: 'Expressa uma masculinidade natural e indomável. Magnético e carismático, para o homem que não tem medo de mostrar sua força interior e mistério.',
    personalityTraits: ['Magnético', 'Carismático', 'Misterioso', 'Forte'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'poder'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2006
  },
  {
    id: 'prada-luna-rossa-black',
    name: 'LUNA ROSSA BLACK',
    brand: 'PRADA',
    gender: 'masculino',
    topNotes: parseNotes('Bergamota, Angelica', 'citrus'),
    heartNotes: parseNotes('Coumarin, Patchouli', 'aromatic'),
    baseNotes: parseNotes('Âmbar, Musk', 'oriental'),
    description: 'Inspirado na Luna Rossa, o catamarã da Prada. Para o homem que desafia limites, combinando tradição com inovação. Intenso e magnético.',
    personalityTraits: ['Desafiador', 'Inovador', 'Intenso', 'Magnético'],
    season: ['outono', 'inverno'],
    occasions: ['noite', 'especial', 'esporte'],
    sillage: 'forte',
    longevity: 'excelente',
    year: 2017
  },
  {
    id: 'hermes-terre-dhermes',
    name: "TERRE D'HERMÈS",
    brand: 'HERMÈS',
    gender: 'masculino',
    topNotes: parseNotes('Laranja, Toranja', 'citrus'),
    heartNotes: parseNotes('Pimenta, Pelargonium, Sílex', 'mineral'),
    baseNotes: parseNotes('Vetiver, Cedro, Benzoin', 'woody'),
    description: 'Uma viagem simbólica às fontes do poder criativo. Terra, essa matéria generosa e acolhedora, que aqui nos fala de território tanto quanto de matéria.',
    personalityTraits: ['Criativo', 'Territorial', 'Generoso', 'Acolhedor'],
    season: ['outono', 'inverno'],
    occasions: ['casual', 'trabalho', 'artístico'],
    sillage: 'moderado',
    longevity: 'excelente',
    year: 2006
  },
  {
    id: 'azzaro-wanted',
    name: 'WANTED',
    brand: 'AZZARO',
    gender: 'masculino',
    topNotes: parseNotes('Cardamomo, Gengibre, Limão', 'spicy'),
    heartNotes: parseNotes('Apple, Lavanda, Gerânio', 'aromatic'),
    baseNotes: parseNotes('Fava Tonka, Ambroxam, Vetiver Haiti', 'woody'),
    description: 'Para o homem procurado - não por crimes, mas por seu charme irresistível. Ousado, carismático e absolutamente viciante.',
    personalityTraits: ['Procurado', 'Charmoso', 'Ousado', 'Viciante'],
    season: ['primavera', 'verão', 'outono'],
    occasions: ['casual', 'noite', 'romântico'],
    sillage: 'forte',
    longevity: 'boa',
    year: 2016
  }
];

export const ALL_PERFUMES = [...FEMININE_PERFUMES, ...MASCULINE_PERFUMES];